services:
  sqlite:
    build:
      context: ./database
    volumes:
      - nutrition-data:/data
      # Mount the entire project directory to /project in read-only mode
      # This lets the container find CSV files wherever they are
      - ./:/project:ro
    command: ["tail", "-f", "/dev/null"]
    healthcheck:
      test: ["CMD", "test", "-f", "/data/.initialized"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - nutrition-data:/data
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_PATH=/data/nutrition.db
    depends_on:
      sqlite:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
    depends_on:
      api:
        condition: service_started
    command: npm run dev

volumes:
  nutrition-data: